import { api } from '../services/api.js';

const missing = (value) => value === null || value === undefined || value === '' || (typeof value === 'number' && !Number.isFinite(value));
const fixed = (value, digits = 2) => missing(value) ? 'N/A' : Number(value).toFixed(digits);
const escape = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const shortFingerprint = (value) => value ? String(value).replace('sha256:', '').slice(0, 12) : 'N/A';
const improvementLabel = (value) => { if (missing(value)) return 'N/A'; const number = Number(value); if (number > 0) return `${fixed(number)}% better`; if (number < 0) return `${fixed(Math.abs(number))}% worse`; return '0.00% change'; };
const yearOptions = (years, selected) => years.map((item) => `<option value="${item.year}" ${item.year === selected ? 'selected' : ''}>${item.year} · ${item.completed_projects} lifecycle projects</option>`).join('');

function overallCard(overall, experiment, production, session) {
  if (!overall || !experiment) return '';
  const paired = overall.paired_project_comparison || {}; const interval = paired.improvement_95pct_ci || [];
  return `<section class="panel"><div class="panel-head"><div><span class="kicker">Fresh same-cohort comparison</span><h2>Production Lifecycle Model vs ${escape(experiment.experiment_name || experiment.experiment_id)}</h2></div></div><div class="detail-financial">
    <div><span>Production Cost MAE</span><strong>${fixed(overall.production_cost_mae)} pp</strong></div><div><span>Experiment Cost MAE</span><strong>${fixed(overall.experiment_cost_mae)} pp</strong></div><div><span>Absolute MAE improvement</span><strong>${fixed(overall.absolute_mae_improvement_pp)} pp</strong></div><div><span>Relative improvement</span><strong>${escape(improvementLabel(overall.improvement_percentage))}</strong></div><div><span>Common held-out projects</span><strong>${fixed(overall.comparison_test_projects, 0)}</strong></div><div><span>Common held-out snapshots</span><strong>${fixed(overall.comparison_test_snapshots, 0)}</strong></div><div><span>Experiment project win rate</span><strong>${missing(paired.experiment_project_win_rate) ? 'N/A' : `${fixed(Number(paired.experiment_project_win_rate) * 100, 1)}%`}</strong></div><div><span>Bootstrap probability experiment is better</span><strong>${missing(paired.probability_candidate_better) ? 'N/A' : `${fixed(Number(paired.probability_candidate_better) * 100, 1)}%`}</strong></div><div><span>Bootstrap 95% interval</span><strong>${interval.length === 2 ? `${fixed(interval[0])}% to ${fixed(interval[1])}%` : 'N/A'}</strong></div><div><span>Training window</span><strong>${session.training_start ?? 'N/A'}–${session.training_end ?? 'N/A'}</strong></div><div><span>Future holdout</span><strong>${session.eligible_test_years?.[0]?.year ?? 'N/A'} onward</strong></div><div><span>Production run ID</span><strong>${escape(production?.run_id || 'N/A')}</strong></div><div><span>Experiment run ID</span><strong>${escape(experiment?.run_id || 'N/A')}</strong></div><div><span>Dataset fingerprint</span><strong title="${escape(production?.dataset_fingerprint || '')}">${escape(shortFingerprint(production?.dataset_fingerprint))}</strong></div>
  </div><div class="notice compact"><strong>Cost MAE is the headline metric.</strong> The experiment remains isolated and is never auto-promoted.</div></section>`;
}

function predictionCard(prediction, actual = null) {
  const comparison = prediction.comparison || {}; const experiment = comparison.experiment || {}; const revealed = actual?.comparison || null;
  return `<section class="panel"><span class="kicker">Same held-out project · both predictions before reveal</span><h2>${escape(prediction.project?.project_name || prediction.project?.project_id || 'Held-out project')}</h2><div class="notice compact"><strong>Production run:</strong> ${escape(prediction.run_id || 'N/A')} · <strong>Experiment run:</strong> ${escape(experiment.experiment_run_id || 'N/A')} · <strong>Experiment:</strong> ${escape(experiment.experiment_name || 'N/A')}</div><div class="model-grid"><article class="panel"><span class="kicker">Production Lifecycle Model</span><div class="detail-financial"><div><span>Predicted cost overrun</span><strong>${fixed(prediction.predicted_cost_overrun)}%</strong></div><div><span>Predicted delay</span><strong>${fixed(prediction.predicted_delay_days)} days</strong></div><div><span>Predicted risk</span><strong>${escape(prediction.predicted_risk || 'N/A')}</strong></div></div></article><article class="panel"><span class="kicker">${escape(experiment.experiment_name || 'Current Experiment')}</span><div class="detail-financial"><div><span>Predicted cost overrun</span><strong>${fixed(experiment.predicted_cost_overrun)}%</strong></div>${!missing(experiment.predicted_delay_days) ? `<div><span>Predicted delay</span><strong>${fixed(experiment.predicted_delay_days)} days</strong></div>` : ''}</div></article></div><div class="notice compact"><strong>Actual final outcome has not been sent to the browser.</strong></div></section>${revealed ? `<section class="panel"><span class="kicker">Official outcome revealed</span><h2>Prediction errors</h2><div class="detail-financial"><div><span>Actual cost overrun</span><strong>${fixed(actual.actual_cost_overrun)}%</strong></div><div><span>Production absolute error</span><strong>${fixed(revealed.production_cost_error_absolute_pp)} pp</strong></div><div><span>Experiment absolute error</span><strong>${fixed(revealed.experiment_cost_error_absolute_pp)} pp</strong></div><div><span>Experiment error change</span><strong>${escape(improvementLabel(revealed.individual_error_improvement_percentage))}</strong></div></div><div class="notice compact"><strong>${revealed.experiment_better_for_project ? 'The experiment was closer on this project.' : 'Production was at least as close on this project.'}</strong></div></section>` : ''}`;
}

export async function ModelSimulationPage(root) {
  const catalog = await api.simulationVersions();
  if (!catalog.lifecycle_data_available) { root.innerHTML = '<header class="page-head"><div><span class="kicker">Judge-controlled historical lifecycle backtest</span><h1>Production vs Experiment Verification</h1></div></header><section class="panel"><div class="error-state">Official PAIMANA lifecycle data is unavailable.</div></section>'; return; }
  const years = catalog.data_years || []; const experimentId = catalog.active_experiment_id || null; const experimentName = catalog.active_experiment_name || 'Current Experiment'; const numbers = years.map((item) => item.year); const saved = api.getActiveLifecycleRun(); const startDefault = numbers.includes(Number(saved?.start_year)) ? Number(saved.start_year) : numbers[0]; const endDefault = numbers.includes(Number(saved?.end_year)) ? Number(saved.end_year) : (numbers.filter((year) => year <= 2015).at(-1) || numbers[Math.max(0, numbers.length - 2)]); const backendReady = Boolean(experimentId && catalog.comparison_backend_available !== false);
  root.innerHTML = `<header class="page-head"><div><span class="kicker">Judge-controlled historical lifecycle backtest</span><h1>Production vs Experiment Verification</h1><p>Both models use the same historical training request and are compared on future held-out projects. Actual outcomes remain hidden until reveal.</p></div></header><div class="notice">${backendReady ? `<strong>Current experiment:</strong> ${escape(experimentName)}` : '<strong>Comparison backend unavailable.</strong> The generic Production vs Experiment session is not advertised by this backend yet.'}</div><section class="panel"><div class="panel-head"><div><span class="kicker">Step 1</span><h2>Retrain & Compare</h2></div></div><div class="filters"><label>Training start year<select id="compare-start">${yearOptions(years, startDefault)}</select></label><label>Training end year<select id="compare-end">${yearOptions(years, endDefault)}</select></label><button class="primary-btn" id="compare-train" ${backendReady ? '' : 'disabled'}>${backendReady ? `Retrain & Compare vs ${escape(experimentName)}` : 'Comparison Backend Unavailable'}</button></div><div id="compare-receipt" class="notice compact">No fresh comparison session is active.</div><div id="compare-overall"></div></section><section class="panel"><div class="panel-head"><div><span class="kicker">Step 2</span><h2>Choose one unseen future project</h2></div></div><div class="filters"><label>Held-out completion year<select id="compare-year" disabled><option>Retrain & Compare first</option></select></label><label>Official held-out project<select id="compare-project" disabled><option>Select a test year first</option></select></label><button class="secondary-btn" id="compare-random" disabled>Pick Random Project</button><button class="primary-btn" id="compare-predict" disabled>Generate Both Predictions</button><button class="secondary-btn" id="compare-reveal" disabled>Reveal Actual Outcome</button></div><div id="compare-note" class="notice compact">Actual outcomes remain server-side until both predictions have been generated.</div></section><div id="compare-output"></div>`;
  const start = root.querySelector('#compare-start'); const end = root.querySelector('#compare-end'); const train = root.querySelector('#compare-train'); const receipt = root.querySelector('#compare-receipt'); const overall = root.querySelector('#compare-overall'); const year = root.querySelector('#compare-year'); const project = root.querySelector('#compare-project'); const random = root.querySelector('#compare-random'); const predict = root.querySelector('#compare-predict'); const reveal = root.querySelector('#compare-reveal'); const note = root.querySelector('#compare-note'); const output = root.querySelector('#compare-output'); let session = null; let projects = []; let prediction = null;
  const clearState = (message = 'No fresh comparison session is active.') => { session = null; projects = []; prediction = null; api.clearActiveLifecycleRun(); year.innerHTML = '<option>Retrain & Compare first</option>'; year.disabled = true; project.innerHTML = '<option>Select a test year first</option>'; project.disabled = true; random.disabled = true; predict.disabled = true; reveal.disabled = true; overall.innerHTML = ''; output.innerHTML = ''; note.innerHTML = `<strong>${escape(message)}</strong>`; };
  const clearPrediction = () => { prediction = null; reveal.disabled = true; output.innerHTML = ''; };
  const loadProjects = async () => { if (!session) return; clearPrediction(); const response = await api.comparisonProjects(session.comparison_session_id || session.session_id, Number(year.value)); projects = response.items || []; project.innerHTML = projects.length ? projects.map((item) => `<option value="${item.record_index}">${escape(item.project_id)} · ${escape(item.project_name)}</option>`).join('') : '<option>No projects available</option>'; project.disabled = !projects.length; random.disabled = !projects.length; predict.disabled = !projects.length; note.innerHTML = `<strong>${projects.length} comparable projects.</strong> ${escape(response.note || '')}`; };
  train.addEventListener('click', async () => { clearState(); train.disabled = true; const startYear = Number(start.value); const endYear = Number(end.value); if (startYear > endYear) { receipt.innerHTML = '<div class="error-state">Training start year cannot be after training end year.</div>'; train.disabled = false; return; } receipt.innerHTML = '<div class="loading">Retraining production and the current experiment. Step 2 is locked until this exact comparison finishes…</div>'; try { const result = await api.retrainAndCompare(startYear, endYear, experimentId); if (!result?.session || !result?.experiment) throw new Error('No fresh comparison session was returned.'); session = result.session; receipt.innerHTML = `<strong>Fresh comparison ready.</strong> Production run ${escape(result.production?.run_id || 'N/A')} · experiment run ${escape(result.experiment?.run_id || 'N/A')}.`; overall.innerHTML = overallCard(result.overall_comparison, result.experiment, result.production, session); api.setActiveLifecycleRun({ comparison_session_id: session.comparison_session_id, start_year: startYear, end_year: endYear, production: result.production, experiment: result.experiment, overall_comparison: result.overall_comparison, dataset_fingerprint: result.production?.dataset_fingerprint }); const eligible = session.eligible_test_years || []; year.innerHTML = eligible.length ? eligible.map((item) => `<option value="${item.year}">${item.year} · ${item.projects} projects</option>`).join('') : '<option>No eligible future years</option>'; year.disabled = !eligible.length; if (eligible.length) await loadProjects(); else note.innerHTML = '<div class="error-state">No common held-out projects are available for this fresh comparison.</div>'; } catch (error) { clearState('No fresh comparison session is active.'); receipt.innerHTML = `<div class="error-state">${escape(error.message)}</div><p class="muted">The failed request cannot restore an earlier session. Retry to create a fresh comparison.</p>`; } finally { train.disabled = false; } });
  year.addEventListener('change', () => loadProjects().catch((error) => clearState(error.message))); project.addEventListener('change', clearPrediction); random.addEventListener('click', () => { if (projects.length) { project.value = String(projects[Math.floor(Math.random() * projects.length)].record_index); clearPrediction(); } }); predict.addEventListener('click', async () => { if (!session || project.disabled) return; clearPrediction(); try { prediction = await api.predictComparison(session.comparison_session_id || session.session_id, Number(project.value)); reveal.disabled = false; output.innerHTML = predictionCard(prediction); } catch (error) { output.innerHTML = `<div class="error-state">${escape(error.message)}</div>`; } }); reveal.addEventListener('click', async () => { if (!session || !prediction) return; reveal.disabled = true; try { const actual = await api.revealComparison(session.comparison_session_id || session.session_id, prediction.record_index); output.innerHTML = predictionCard(prediction, actual); } catch (error) { output.innerHTML += `<div class="error-state">${escape(error.message)}</div>`; reveal.disabled = false; } });
}
