import { api } from '../services/api.js';
import { horizontalBars, lineChart } from '../components/charts.js';

const fixed = (value, digits = 2) => Number(value || 0).toFixed(digits);
const escape = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const errorBuckets = (rows, key) => [[0, 10], [10, 30], [30, 60], [60, Infinity]].map(([from, to]) => ({ label: `${from}–${to === Infinity ? '∞' : to}`, value: rows.filter((row) => Math.abs(Number(row[key])) >= from && Math.abs(Number(row[key])) < to).length }));

function sortableTable(rows, reveal) {
  return `<div class="table-wrap"><table class="data-table" id="simulation-table"><thead><tr><th data-sort="project_id">Project ↕</th><th data-sort="sector">Sector ↕</th><th data-sort="predicted_cost_overrun">Predicted cost ↕</th><th data-sort="actual_cost_overrun">Actual cost ↕</th><th data-sort="cost_error">Cost error ↕</th><th data-sort="predicted_delay_days">Predicted delay ↕</th><th data-sort="actual_delay_days">Actual delay ↕</th><th data-sort="delay_error">Delay error ↕</th><th>Risk</th></tr></thead><tbody>${rows.map((row) => `<tr><td><strong>${escape(row.project_id)}</strong><small>${escape(row.project_name)}</small></td><td>${escape(row.sector)}</td><td>${fixed(row.predicted_cost_overrun)}%</td><td>${reveal ? `${fixed(row.actual_cost_overrun)}%` : 'Hidden'}</td><td>${reveal ? `${fixed(row.cost_error)} pp` : '—'}</td><td>${fixed(row.predicted_delay_days)} days</td><td>${reveal ? `${fixed(row.actual_delay_days)} days` : 'Hidden'}</td><td>${reveal ? `${fixed(row.delay_error)} days` : '—'}</td><td>${row.predicted_risk}${reveal ? ` / ${row.actual_risk}` : ''}</td></tr>`).join('')}</tbody></table></div>`;
}

export async function ModelSimulationPage(root) {
  const versions = await api.simulationVersions();
  root.innerHTML = `<header class="page-head"><div><span class="kicker">Official completed-project archive</span><h1>Model Simulation</h1><p>This simulation predicts future outcomes using only information available at the selected historical point.</p></div></header><div class="notice"><strong>No synthetic data:</strong> outcome metrics use official PAIMANA completed-project reports. V2 years without recorded completed outcomes stay forecast-only and are excluded from reliability metrics.</div><section class="panel"><div class="filters"><label>Training period <select id="simulation-version">${versions.items.map((version) => `<option value="${version.key}">${version.training_label} Model</option>`).join('')}</select></label><button class="primary-btn" id="run-simulation">Run Historical Forecast</button><button class="secondary-btn" id="reveal-actual" disabled>Reveal Actual Outcome</button></div><div id="simulation-window" class="notice compact"></div><div id="simulation-output" class="loading">Choose a model window, then run the historical forecast.</div></section>`;
  const select = root.querySelector('#simulation-version'); const output = root.querySelector('#simulation-output'); const revealButton = root.querySelector('#reveal-actual'); let state = null; let reveal = false;
  const drawWindow = () => { const version = versions.items.find((item) => item.key === select.value); root.querySelector('#simulation-window').innerHTML = `<strong>Training data:</strong> ${version.training_label} · <strong>Testing data:</strong> ${version.testing_label}. ${version.available_actual_end ? `Official outcomes are available through ${version.available_actual_end}.` : ''}`; };
  const draw = () => {
    const { metrics, items } = state;
    output.innerHTML = `<div class="stat-grid"><article class="stat-card blue"><span class="stat-eyebrow">Cost MAE</span><strong class="stat-value">${fixed(metrics.cost_model.MAE)} pp</strong><small>RMSE ${fixed(metrics.cost_model.RMSE)} · MAPE ${fixed(metrics.cost_model.MAPE)}%</small></article><article class="stat-card amber"><span class="stat-eyebrow">Delay MAE</span><strong class="stat-value">${fixed(metrics.delay_model.MAE_days)} days</strong><small>RMSE ${fixed(metrics.delay_model.RMSE_days)} days</small></article><article class="stat-card green"><span class="stat-eyebrow">Risk F1</span><strong class="stat-value">${fixed(metrics.risk_model.f1 * 100, 1)}%</strong><small>Accuracy ${fixed(metrics.risk_model.accuracy * 100, 1)}%</small></article></div><div class="model-grid"><section class="panel"><h3>Cost overrun comparison</h3><h4>AI predicted</h4>${lineChart(items.map((row) => ({ label: row.project_id, value: row.predicted_cost_overrun })), { suffix: '%' })}${reveal ? `<h4>Official recorded outcome</h4>${lineChart(items.map((row) => ({ label: row.project_id, value: row.actual_cost_overrun })), { suffix: '%' })}` : ''}</section><section class="panel"><h3>Delay comparison</h3><h4>AI predicted</h4>${lineChart(items.map((row) => ({ label: row.project_id, value: row.predicted_delay_days })), { suffix: ' days' })}${reveal ? `<h4>Official recorded outcome</h4>${lineChart(items.map((row) => ({ label: row.project_id, value: row.actual_delay_days })), { suffix: ' days' })}` : ''}</section></div>${reveal ? `<div class="model-grid"><section class="panel"><h3>Cost error distribution</h3>${horizontalBars(errorBuckets(items, 'cost_error'), { format: (v) => `${v} projects` })}</section><section class="panel"><h3>Delay error distribution</h3>${horizontalBars(errorBuckets(items, 'delay_error'), { format: (v) => `${v} projects` })}</section></div>` : '<div class="notice compact">Predictions are shown first. Reveal the official recorded outcome to compare errors.</div>'}<section class="panel"><div class="panel-head"><div><span class="kicker">${items.length} official completed projects</span><h2>Prediction vs actual comparison</h2></div></div>${sortableTable(items, reveal)}</section><section class="panel"><div class="panel-head"><div><span class="kicker">Selected completed-project record</span><h2>Individual project forecast</h2></div></div><select id="simulation-project">${items.map((row, index) => `<option value="${index}">${escape(row.project_id)} · ${escape(row.project_name)}</option>`).join('')}</select><div id="simulation-project-detail"></div></section>`;
    const projectDetail = () => { const row = items[Number(root.querySelector('#simulation-project').value)]; root.querySelector('#simulation-project-detail').innerHTML = `<div class="detail-summary"><div class="detail-financial"><div><span>Approved cost</span><strong>₹${fixed(row.snapshot.approved_cost_cr)} Cr</strong></div><div><span>Sector</span><strong>${escape(row.snapshot.sector)}</strong></div><div><span>AI cost overrun</span><strong>${fixed(row.predicted_cost_overrun)}%</strong></div><div><span>AI delay</span><strong>${fixed(row.predicted_delay_days)} days</strong></div></div></div><div class="notice compact">${escape(row.snapshot.note)}</div><h3>SHAP explanation</h3>${horizontalBars(row.shap_explanation.map((factor) => ({ label: `${factor.feature} (${factor.direction})`, value: Math.abs(factor.impact) })), { format: (v) => fixed(v, 3) })}${reveal ? `<div class="notice compact"><strong>Official outcome:</strong> ${fixed(row.actual_cost_overrun)}% reported cost overrun; ${fixed(row.actual_delay_days)} days reported delay. Errors: ${fixed(row.cost_error)} pp and ${fixed(row.delay_error)} days.</div>` : ''}`; };
    root.querySelector('#simulation-project').addEventListener('change', projectDetail); projectDetail();
    root.querySelectorAll('#simulation-table th[data-sort]').forEach((head) => head.addEventListener('click', () => { const key = head.dataset.sort; items.sort((a, b) => String(a[key]).localeCompare(String(b[key]), undefined, { numeric: true })); draw(); }));
  };
  drawWindow(); select.addEventListener('change', drawWindow);
  root.querySelector('#run-simulation').addEventListener('click', async () => { output.innerHTML = '<div class="loading">Running selected historical model on unseen official outcomes…</div>'; reveal = false; revealButton.disabled = true; try { state = await api.runSimulation(select.value); revealButton.disabled = false; draw(); } catch (error) { output.innerHTML = `<div class="error-state">${escape(error.message)}</div>`; } });
  revealButton.addEventListener('click', () => { reveal = true; draw(); });
}
