import { api } from '../services/api.js';
import { horizontalBars } from '../components/charts.js';

const fixed = (value, digits = 2) => Number(value || 0).toFixed(digits);
const escape = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

function snapshotCard(snapshot) {
  const unavailable = 'Not reported';
  return `<div class="detail-summary"><div class="detail-financial"><div><span>Approved cost</span><strong>₹${fixed(snapshot.approved_cost_cr)} Cr</strong></div><div><span>Planned completion</span><strong>${escape(snapshot.planned_commissioning_date || unavailable)}</strong></div><div><span>Sector</span><strong>${escape(snapshot.sector || unavailable)}</strong></div><div><span>Agency</span><strong>${escape(snapshot.implementing_agency || unavailable)}</strong></div></div></div>`;
}

function resultCard(item, reveal) {
  const factors = item.shap_explanation.map((factor) => ({ label: `${factor.feature} (${factor.direction})`, value: Math.abs(factor.impact) }));
  return `<section class="panel"><div class="panel-head"><div><span class="kicker">Live historical inference</span><h2>${escape(item.project_name)}</h2><p class="muted">${escape(item.project_id)} · ${escape(item.sector)}</p></div><span class="risk-badge risk-${item.predicted_risk.toLowerCase()}">${item.predicted_risk} predicted risk</span></div>${snapshotCard(item.snapshot)}<div class="notice compact">${escape(item.snapshot.note)}</div><div class="detail-summary"><div class="detail-financial"><div><span>AI cost overrun</span><strong>${fixed(item.predicted_cost_overrun)}%</strong></div><div><span>AI delay</span><strong>${fixed(item.predicted_delay_days)} days</strong></div><div><span>Cost outcome</span><strong>${reveal ? `${fixed(item.actual_cost_overrun)}%` : 'Hidden'}</strong></div><div><span>Delay outcome</span><strong>${reveal ? `${fixed(item.actual_delay_days)} days` : 'Hidden'}</strong></div></div></div><h3>SHAP explanation</h3>${horizontalBars(factors, { format: (value) => fixed(value, 3) })}${reveal ? `<div class="notice compact"><strong>Official recorded outcome:</strong> Cost error ${fixed(item.cost_error)} percentage points; delay error ${fixed(item.delay_error)} days. Risk: ${item.predicted_risk} predicted / ${item.actual_risk} actual.</div>` : '<div class="notice compact">The prediction above was generated for this selected project. Click Reveal Actual Outcome to compare it with the official historical record.</div>'}</section>`;
}

export async function ModelSimulationPage(root) {
  const versions = await api.simulationVersions();
  root.innerHTML = `<header class="page-head"><div><span class="kicker">Official completed-project archive</span><h1>Model Simulation</h1><p>Choose one historical project, run the selected model in front of you, then reveal its official outcome.</p></div></header><div class="notice"><strong>No synthetic data:</strong> this flow runs a selected registered model on one official PAIMANA completed-project record. Completion expenditure and date are targets, never inputs.</div><section class="panel"><div class="filters"><label>Training period <select id="simulation-version">${versions.items.map((version) => `<option value="${version.key}">${version.training_label} Model</option>`).join('')}</select></label><label>Historical project <select id="simulation-project" disabled><option>Loading projects…</option></select></label><button class="primary-btn" id="run-simulation" disabled>Run Historical Forecast</button><button class="secondary-btn" id="reveal-actual" disabled>Reveal Actual Outcome</button></div><div id="simulation-window" class="notice compact"></div><div id="simulation-output" class="empty-state"><strong>Select a project</strong><span>Choose a historical window and completed project, then run its forecast.</span></div></section>`;
  const versionSelect = root.querySelector('#simulation-version'); const projectSelect = root.querySelector('#simulation-project'); const runButton = root.querySelector('#run-simulation'); const revealButton = root.querySelector('#reveal-actual'); const output = root.querySelector('#simulation-output'); let state = null; let reveal = false;
  const windowNote = () => { const version = versions.items.find((item) => item.key === versionSelect.value); root.querySelector('#simulation-window').innerHTML = `<strong>Training data:</strong> ${version.training_label} · <strong>Evaluation data:</strong> ${version.testing_label}. Official outcomes are available through ${version.available_actual_end}; later years remain forecast-only.`; };
  const loadProjects = async () => { windowNote(); runButton.disabled = true; projectSelect.disabled = true; projectSelect.innerHTML = '<option>Loading eligible historical projects…</option>'; try { const data = await api.simulationProjects(versionSelect.value); projectSelect.innerHTML = data.items.map((project) => `<option value="${project.record_index}">${escape(project.project_id)} · ${escape(project.project_name)} (${escape(project.sector)})</option>`).join(''); projectSelect.disabled = false; runButton.disabled = false; } catch (error) { projectSelect.innerHTML = `<option>${escape(error.message)}</option>`; } };
  const draw = () => { output.innerHTML = `<div class="stat-grid"><article class="stat-card blue"><span class="stat-eyebrow">Window cost MAE</span><strong class="stat-value">${fixed(state.metrics.cost_model.MAE)} pp</strong><small>Historical reliability across this model window</small></article><article class="stat-card amber"><span class="stat-eyebrow">Window delay MAE</span><strong class="stat-value">${fixed(state.metrics.delay_model.MAE_days)} days</strong><small>Historical reliability across this model window</small></article><article class="stat-card green"><span class="stat-eyebrow">Risk F1</span><strong class="stat-value">${fixed(state.metrics.risk_model.f1 * 100, 1)}%</strong><small>Official completed-project evaluation</small></article></div>${resultCard(state.item, reveal)}`; };
  versionSelect.addEventListener('change', async () => { state = null; reveal = false; revealButton.disabled = true; output.innerHTML = '<div class="empty-state"><strong>Select a project</strong><span>Loading the selected historical evaluation cohort.</span></div>'; await loadProjects(); });
  runButton.addEventListener('click', async () => { reveal = false; revealButton.disabled = true; output.innerHTML = '<div class="loading">Loading selected model → preparing official project fields → predicting cost, delay, and risk…</div>'; try { state = await api.runSimulation(versionSelect.value, projectSelect.value); revealButton.disabled = false; draw(); } catch (error) { output.innerHTML = `<div class="error-state">${escape(error.message)}</div>`; } });
  revealButton.addEventListener('click', () => { reveal = true; draw(); });
  await loadProjects();
}
