import { api } from '../services/api.js';
import { peerBenchmark } from '../features/projects/PeerBenchmark.js';
import { moneyCr, dateHuman, pct, daysHuman } from '../utils/format.js';
import { progressRing } from '../components/charts.js';

export async function ProjectDetailPage(root, code) {
  const [project,forecast,peers] = await Promise.all([api.project(code),api.forecast(code),api.peers(code)]);
  root.innerHTML=`<header class="page-head detail-head"><div><a class="back-link" href="#/projects">← Projects</a><span class="kicker">#${project.project_code} · ${project.sector}</span><h1>${project.project_name}</h1><p>${project.ministry}</p></div><a class="secondary-btn" href="#/scenario?project=${project.project_code}">Run scenario</a></header>
  <div class="detail-summary panel"><div class="detail-financial"><div><span>Original cost</span><strong>${moneyCr(project.original_cost_cr)}</strong></div><div><span>Revised cost</span><strong>${moneyCr(project.revised_cost_cr)}</strong></div><div><span>Cumulative expenditure</span><strong>${moneyCr(project.expenditure_cr)}</strong></div><div><span>Cost escalation</span><strong>${pct(project.cost_escalation_pct)}</strong></div></div>
  <div class="detail-rings">${progressRing(project.financial_progress_pct,'financial','progress')}${progressRing(project.physical_progress_pct,'physical','progress')}</div></div>
  <div class="project-meta panel"><div><span>Original completion</span><strong>${dateHuman(project.original_end_date)}</strong></div><div><span>Revised completion</span><strong>${dateHuman(project.revised_end_date)}</strong></div><div><span>Observed extension</span><strong>${daysHuman(project.schedule_extension_days)}</strong></div><div><span>Temporal risk level</span><strong>${forecast.risk_level}</strong></div></div>
  <section class="risk-panel panel"><div class="panel-head"><div><span class="kicker">Temporal forecast</span><h2>Future outcome prediction</h2></div><span class="risk-badge risk-${forecast.risk_level.toLowerCase()}"><span class="risk-dot"></span>${forecast.risk_score}/100</span></div><div class="risk-grid"><div class="risk-metric"><span>Expected cost increase</span><strong>${pct(forecast.predicted_cost_overrun_percentage)}</strong></div><div class="risk-metric"><span>Expected delay</span><strong>${daysHuman(forecast.predicted_delay_days)}</strong></div><div class="risk-metric"><span>Progress gap</span><strong>${pct(forecast.current_status.progress_delay_percentage_points)}</strong></div><div class="risk-metric"><span>Snapshot</span><strong>${forecast.current_status.snapshot_month}</strong></div></div><div class="notice compact">${forecast.model_scope}</div></section>${peerBenchmark(peers,project)}
  <section class="source-note"><span>Source</span><a href="${project.source_url}" target="_blank" rel="noreferrer">Official PAIMANA public dashboard ↗</a></section>`;
}
